// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("TomatoTime")>]
[<assembly: AssemblyProductAttribute("TomatoTime")>]
[<assembly: AssemblyDescriptionAttribute("Timer and Clock app")>]
[<assembly: AssemblyVersionAttribute("1.0.1")>]
[<assembly: AssemblyFileVersionAttribute("1.0.1")>]
[<assembly: AssemblyConfigurationAttribute("Release")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "TomatoTime"
    let [<Literal>] AssemblyProduct = "TomatoTime"
    let [<Literal>] AssemblyDescription = "Timer and Clock app"
    let [<Literal>] AssemblyVersion = "1.0.1"
    let [<Literal>] AssemblyFileVersion = "1.0.1"
    let [<Literal>] AssemblyConfiguration = "Release"
